import fs from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const configPath = path.join(root, 'sites-config.js');

function decodeJsString(value) {
  return value
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, '\r')
    .replace(/\\t/g, '\t')
    .replace(/\\(['"\\])/g, '$1');
}

function parseSitesConfig(source) {
  const sites = [];
  const blockRe = /([A-Za-z0-9_-]+)\s*:\s*Object\.freeze\(\{([\s\S]*?)\}\)\s*,?/g;
  let m;
  while ((m = blockRe.exec(source))) {
    const body = m[2];
    const titleMatch = body.match(/SEO_TITLE\s*:\s*(['"])([\s\S]*?)\1/);
    const descMatch = body.match(/SEO_DESCRIPTION\s*:\s*(['"])([\s\S]*?)\1/);
    if (!titleMatch && !descMatch) continue;
    sites.push({
      key: m[1],
      title: decodeJsString((titleMatch?.[2] || '').trim()),
      description: decodeJsString((descMatch?.[2] || '').trim())
    });
  }
  return sites;
}

function htmlText(value) {
  return String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}
function attr(value) {
  return htmlText(value).replace(/"/g,'&quot;').replace(/'/g,'&#39;').replace(/\r?\n/g,' ');
}
function siteIndexPath(key) {
  return key === 'district' ? path.join(root, 'index.html') : path.join(root, key, 'index.html');
}
function updateHtml(html, title, description) {
  const safeTitle = htmlText(title);
  const safeDesc = attr(description);
  const titleTag = `<title data-lp360-config-seo="title">${safeTitle}</title>`;
  const descTag = `<meta name="description" content="${safeDesc}" data-lp360-config-seo="description" />`;

  if (/<title(?:\s[^>]*)?>[\s\S]*?<\/title>/i.test(html)) {
    html = html.replace(/<title(?:\s[^>]*)?>[\s\S]*?<\/title>/i, titleTag);
  } else {
    html = html.replace(/<\/head>/i, `  ${titleTag}\n</head>`);
  }
  if (/<meta\s+[^>]*name=["']description["'][^>]*>/i.test(html)) {
    html = html.replace(/<meta\s+[^>]*name=["']description["'][^>]*>/i, descTag);
  } else {
    html = html.replace(titleTag, `${descTag}\n  ${titleTag}`);
  }

  // Remove only SEO tags previously generated by this tool/older LP360 SEO tools.
  html = html.replace(/\n?\s*<meta\s+[^>]*data-lp360-(?:static-seo|config-og)=["']1["'][^>]*\/?\s*>/gi, '');
  const og = [
    `<meta property="og:title" content="${attr(title)}" data-lp360-config-og="1" />`,
    `<meta property="og:description" content="${safeDesc}" data-lp360-config-og="1" />`,
    `<meta property="og:type" content="website" data-lp360-config-og="1" />`
  ].map(x => `  ${x}`).join('\n');
  return html.replace(descTag, `${descTag}\n${og}`);
}

const source = await fs.readFile(configPath, 'utf8');
const sites = parseSitesConfig(source);
if (!sites.length) throw new Error('ไม่พบ SEO_TITLE / SEO_DESCRIPTION ใน sites-config.js');

let changed = 0;
let failed = 0;
for (const site of sites) {
  const indexPath = siteIndexPath(site.key);
  try { await fs.access(indexPath); }
  catch { console.log(`[skip] ${site.key}: ไม่มี ${path.relative(root,indexPath)}`); continue; }
  if (!site.title || !site.description) {
    console.error(`[error] ${site.key}: SEO_TITLE หรือ SEO_DESCRIPTION ว่างใน sites-config.js`);
    failed++;
    continue;
  }
  const before = await fs.readFile(indexPath, 'utf8');
  const after = updateHtml(before, site.title, site.description);
  if (after !== before) {
    await fs.writeFile(indexPath, after, 'utf8');
    changed++;
    console.log(`[updated] ${site.key}: ${site.title}`);
  } else {
    console.log(`[unchanged] ${site.key}`);
  }
}
console.log(`Static SEO from sites-config complete: changed=${changed}, failed=${failed}`);
if (failed) process.exitCode = 1;
