(() => {
  'use strict';

  function currentUserKey() {
    const name = (location.pathname.split('/').pop() || '').replace(/\.html?$/i, '');
    return name || '1';
  }

  function escapeText(value) {
    return String(value == null ? '' : value);
  }

  const key = currentUserKey();
  const pages = window.LP360_USER_PAGES_CONFIG || {};
  const cfg = pages[key];
  const frame = document.getElementById('lp360UserFrame');
  const error = document.getElementById('lp360UserConfigError');

  if (!cfg || !cfg.EXEC_URL) {
    if (frame) frame.hidden = true;
    if (error) {
      error.hidden = false;
      error.textContent = 'ยังไม่ได้กำหนด USER_PAGES[\'' + key + '\'] ใน sites-config.js';
    }
    return;
  }

  // Browser runtime fallback. LINE/social preview uses the static tags generated by GitHub Action.
  if (cfg.SEO_TITLE) document.title = escapeText(cfg.SEO_TITLE);
  const desc = document.querySelector('meta[name="description"]');
  if (desc && cfg.SEO_DESCRIPTION) desc.setAttribute('content', escapeText(cfg.SEO_DESCRIPTION));

  frame.src = cfg.EXEC_URL;
  frame.hidden = false;
})();
